name: Publish Docker Image

# El trigger ocurre cuando se crea un nuevo tag
on:
  push:
    tags:
      - 'v*'  # Este patrón captura cualquier tag que comience con 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # La ruta al archivo Dockerfile
          platforms: linux/amd64  # Plataforma de destino
          push: true  # Empuja la imagen a Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-repo:${{ github.ref_name }}  # Usa el tag de Git como versión
